### ISSUE TITLE
Access token is expired

### ISSUE THREAD

**Issue by cassidoo** [codingbrent/clarifai-nsfw-detection-csharp#1]
It might be worth it to have an environment variables file (not checked into git) with the Client ID and Client Secret so that you can call the `/token` endpoint whenever the token has expired after 24 hours.

**Comment by brentru** [comment]
Cassidoo,

Thanks for looking at this project! I will work on fixing these issues and close this issue once implemented. It's an project that I did for fun during the semester but now that I'm off, I'll correct it. Great API btw!

**Comment by cassidoo** [comment]
Awesome.  Congrats on finishing another semester! :)
